@startuml lab_3_generate_by_ngrams.main
!pragma useIntermediatePackages false

class lab_3_generate_by_ngrams.main.TextProcessor {
  _end_of_word_token: str
  _storage: None
}
class lab_3_generate_by_ngrams.main.NGramLanguageModel {
  _n_gram_size: int
  _n_gram_frequencies: None
  _encoded_corpus: tuple | None
}
class lab_3_generate_by_ngrams.main.GreedyTextGenerator {
  _model: NGramLanguageModel
  _text_processor: TextProcessor
}
class lab_3_generate_by_ngrams.main.BeamSearcher {
  _beam_width: int
  _model: NGramLanguageModel
}
class lab_3_generate_by_ngrams.main.BeamSearchTextGenerator {
  _language_model: NGramLanguageModel
  _text_processor: TextProcessor
  _beam_width: int
  beam_searcher: None
}
class lab_3_generate_by_ngrams.main.NGramLanguageModelReader {
  _json_path: str
  _eow_token: str
  _content: None
  _text_processor: None
}
class lab_3_generate_by_ngrams.main.BackOffGenerator {
  _language_models: None
  _text_processor: TextProcessor
}
lab_3_generate_by_ngrams.main.GreedyTextGenerator *-- lab_3_generate_by_ngrams.main.NGramLanguageModel
lab_3_generate_by_ngrams.main.GreedyTextGenerator *-- lab_3_generate_by_ngrams.main.TextProcessor
lab_3_generate_by_ngrams.main.BeamSearcher *-- lab_3_generate_by_ngrams.main.NGramLanguageModel
lab_3_generate_by_ngrams.main.BeamSearchTextGenerator *-- lab_3_generate_by_ngrams.main.NGramLanguageModel
lab_3_generate_by_ngrams.main.BeamSearchTextGenerator *-- lab_3_generate_by_ngrams.main.TextProcessor
lab_3_generate_by_ngrams.main.BackOffGenerator *-- lab_3_generate_by_ngrams.main.TextProcessor
footer Generated by //py2puml//
@enduml
