# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

import os
import sys

sys.path.insert(0, os.path.abspath('..'))

project = 'Программирование для лингвистов'
copyright = '2023, Демидовский А.В. и другие'
author = 'Демидовский А.В. и другие'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    'sphinx_design',
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'docxbuilder',
    'sphinx.ext.napoleon',
    'sphinx_tabs.tabs',
    'notfound.extension'
]

templates_path = ['_templates']
exclude_patterns = []

# Template used to render the 404.html generated by this extension.
# notfound_template = "404.html"

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']
html_css_files = ['css/custom.css']
# html_title = project
html_logo = '_static/fal_logo.jpeg'
