name: Documentation Check

on:
  pull_request:
  push:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.13.11'

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Build Documentation
        run: |
          export PYTHONPATH=$(pwd):$PYTHONPATH
          rm -rf source/build/
          sphinx-build -W -n -b html source/ source/build/
